- name: Switch context to homelab namespace
  ansible.builtin.shell:
  cmd: |
    kubectl config use-context homelab

- name: Deploy pod security policy
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}tkgs_psp.yaml"
    # kubeconfig: "{{ kubeconfig }}"

- name: Create kubeconfig
  ansible.builtin.shell:
    cmd: >
      kubectl get secret {{ clustername }}-kubeconfig
      -o jsonpath='{.data.value}' | base64 -d > /var/tmp/tanzu.yaml

- name: Switch context to cluster namespace
  ansible.builtin.shell:
    cmd: |
      kubectl config use-context {{ clustername }}

- name: Deploy packagerepo
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}tkgs_cluster_setup.yaml"
    kubeconfig: "{{ kubeconfig }}"

- name: Deploy cert-manager PackageInstall
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}cert-manager.yaml"
    kubeconfig: "{{ kubeconfig }}"

- name: Deploy contour PackageInstall
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}contour.yaml"
    kubeconfig: "{{ kubeconfig }}"
