- name: Copy manifests to localhost
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"
  
- name: Login to tanzu using kubectl vsphere
  ansible.builtin.shell:
    cmd: >
      kubectl vsphere login
      --server={{ tanzu_cp }}
      --vsphere-username {{ vsphere_username }}
      --insecure-skip-tls-verify
      --tanzu-kubernetes-cluster-name {{ clustername }}
      --tanzu-kubernetes-cluster-namespace homelab
  environment:
    KUBECTL_VSPHERE_PASSWORD: "{{ vsphere_password }}"

- name: Switch context to homelab namespace
  ansible.builtin.shell:
    cmd: |
      kubectl config use-context homelab

- name: Create kubeconfig
  ansible.builtin.shell:
    cmd: >
      kubectl get secret {{ clustername }}-kubeconfig
      -o jsonpath='{.data.value}' | base64 -d > /var/tmp/tanzu.yaml

- name: Switch context to cluster namespace
  ansible.builtin.shell:
    cmd: |
      kubectl config use-context {{ clustername }}

- name: Deploy pod security policy
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}tkgs_psp.yaml"
    # kubeconfig: "{{ kubeconfig }}"

- name: Deploy packagerepo
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}packagerepo.yaml"
    # kubeconfig: "{{ kubeconfig }}"

- name: Deploy cert-manager PackageInstall
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}cert-manager.yaml"
    # kubeconfig: "{{ kubeconfig }}"

- name: Deploy contour PackageInstall
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}contour.yaml"
    # kubeconfig: "{{ kubeconfig }}"
