- name: Create vmware-exporter-deployment.yaml manifest on host
  ansible.builtin.template:
    src: vmware-exporter-deployment.yaml.j2
    dest: "{{ dest }}vmware-exporter-deployment.yaml"

- name: Deploy vmware-exporter
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - vmware-exporter-service.yaml
    - vmware-exporter-deployment.yaml
    - vmware-exporter-ingress.yaml