---
- name: Set build env
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Set cluster env
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: cluster_env

- name: Install k3s control plane on first node (cluster-init)
  hosts: "{{ hostvars['localhost']['cp_nodes'][0] | default([]) }}"
  gather_facts: true
  become: true

  tasks:

    - name: Run k3s prereq role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: prereq

    - name: Run control plane role with cluster-init
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: control_plane

    - name: Create kubeconfig secret in hashi vault
      ansible.builtin.include_role:
        name: eingram23.kubernetes.kubeconfig
        tasks_from: k3s_to_vault

    - name: Deploy vsphere-csi (needed to remove uninitialized taint)
      when: "'vsphere_csi' in hostvars['localhost']['base_components']"
      delegate_to: localhost
      block:
        - name: Create kubeconfig in $HOME/.kube
          ansible.builtin.include_role:
            name: eingram23.kubernetes.kubeconfig
            tasks_from: create_local_kube

        - name: Run vsphere_csi role
          ansible.builtin.include_role:
            name: eingram23.kubernetes.vsphere_csi

- name: Install k3s control plane on remaining nodes
  hosts: "{{ hostvars['localhost']['cp_nodes']['range(2, cp_count | int + 1)'] | default([]) }}"
  gather_facts: true
  become: true

  tasks:

    - name: Run k3s prereq role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: prereq

    - name: Run control plane role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: control_plane

    # - name: Create kubeconfig secret in hashi vault
    #   ansible.builtin.include_role:
    #     name: eingram23.kubernetes.kubeconfig
    #     tasks_from: k3s_to_vault

- name: Post k3s install tasks
  hosts: localhost
  gather_facts: true
  become: false

  tasks:

    - name: Deploy base components
      ansible.builtin.include_role:
        name: eingram23.kubernetes.{{ component_item }}
      loop: "{{ base_components }}"
      loop_control:
        loop_var: component_item

- name: Install k3s worker nodes
  hosts: "{{ hostvars['localhost']['worker_nodes'] | default([]) }}"
  gather_facts: true
  become: true

  tasks:

    - name: Run k3s prereq role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: prereq

    - name: Install worker nodes
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: worker

- name: Deploy k3s-metrics-service
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Deploy k3s-metrics-service
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: k3s-metrics-service
