---
- name: Set build env
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Set build env
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: build_env

- name: Install k3s control plane
  hosts: "{{ hostvars['localhost']['cp_nodes'] | default([]) }}"
  gather_facts: true
  become: true

  tasks:

    - name: Run k3s prereq role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: prereq

    - name: Run control plane role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: control_plane

    - name: Create kubeconfig secret in hashi vault
      ansible.builtin.include_role:
        name: eingram23.kubernetes.kubeconfig
        tasks_from: k3s_to_vault
      run_once: true

- name: Install k3s worker nodes
  hosts: "{{ hostvars['localhost']['worker_nodes'] | default([]) }}"
  gather_facts: true
  become: true

  tasks:

    - name: Run k3s prereq role
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: prereq

    - name: Install worker nodes
      ansible.builtin.include_role:
        name: eingram23.kubernetes.k3s
        tasks_from: worker

- name: Post k3s install tasks
  hosts: localhost
  gather_facts: true
  become: false

  tasks:

    - name: Create kubeconfig in $HOME/.kube
      ansible.builtin.include_role:
        name: eingram23.kubernetes.kubeconfig
        tasks_from: create_local_kube

    - name: Deploy base components
      ansible.builtin.include_role:
        name: eingram23.kubernetes.{{ component_item }}
      loop: "{{ base_components }}"
      loop_control:
        loop_var: component_item
