- name: Download files to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"

- name: Add grafana_agent_operator chart repo
  kubernetes.core.helm_repository:
    name: grafana_agent_operator
    repo_url: "https://grafana.github.io/helm-charts"

- name: Install hashicorp/vault chart from repo
  kubernetes.core.helm:
    release_name: grafana-agent-operator
    release_namespace: grafana
    create_namespace: true
    chart_ref: grafana_agent_operator/grafana-agent-operator
    chart_version: "{{ ver }}"
    wait: true
    update_repo_cache: true
    values_files: "{{ dest }}grafana-values.yaml"
    kubeconfig: "{{ kubeconfig }}"

- name: Deploy grafana_agent manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - grafanaAgent.yaml
    - metricsInstance.yaml
    - kubeletServiceMonitor.yaml
    - cAdvisorServiceMonitor.yaml
    - logsInstance.yaml
    - podLogs.yaml
    - node_exporter.yaml