- name: Download files to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"

- name: Create templated files on host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ dest }}{{ item }}"
    mode: '0644'
  loop:
    - kube-state-metrics.yaml
    - grafana-agent.yaml
    - grafana-values.yaml

- name: Add grafana_agent_operator chart repo
  kubernetes.core.helm_repository:
    name: grafana_agent_operator
    repo_url: "https://grafana.github.io/helm-charts"

- name: Install grafana-agent-operator chart from repo
  kubernetes.core.helm:
    release_name: grafana-agent-operator
    release_namespace: grafana
    create_namespace: true
    chart_ref: grafana_agent_operator/grafana-agent-operator
    chart_version: "{{ ver }}"
    wait: true
    update_repo_cache: true
    values_files: "{{ dest }}grafana-values.yaml"
    # kubeconfig: "{{ kubeconfig }}"

- name: Deploy grafana_agent manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    # kubeconfig: "{{ kubeconfig }}"
  loop:
    - grafana-agent.yaml
    - metrics-instance.yaml
    - kubelet-servicemonitor.yaml
    - cadvisor-servicemonitor.yaml
    - logs-instance.yaml
    - pod-logs.yaml
    - node-exporter.yaml
    - eventhandler.yaml
    - kube-state-metrics.yaml
    - longhorn-servicemonitor.yaml