kind: Service
apiVersion: v1
metadata:
  name: calibre
  namespace: calibre
spec:
  selector:
    app: calibre
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: calibre
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: calibre-admin    
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: calibre-web
  type: LoadBalancer
