- name: Copy definition to master node
  ansible.builtin.copy:
    src: "{{ manifest }}.yaml"
    dest: /opt/kubernetes/defs/{{ manifest }}.yaml
    mode: '0644'

- name: Delete from manifest
  kubernetes.core.k8s:
    state: absent
    src: /opt/kubernetes/defs/{{ manifest }}.yaml
    # kubeconfig: /etc/rancher/k3s/k3s.yaml
