---
- name: Create staging folders
  ansible.builtin.file:
    path: "{{ dest }}"
    state: directory
    mode: '0755'

- name: Download longhorn-iscsi-install manifest
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/longhorn/longhorn/v{{ longhorn_ver }}/deploy/prerequisite/longhorn-iscsi-installation.yaml"
    dest: "{{ dest }}{{ iscsi_manifest }}"
    mode: '0644'

- name: Deploy longhorn-iscsi-install DaemonSet
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: "{{ dest }}{{ iscsi_manifest }}"
