---
- name: Install longhorn on k3s
  hosts: "{{ hostvar }}"
  gather_facts: false
  become: false

  tasks:

    - name: Deploy longhorn-iscsi-install manifest
      ansible.builtin.include_role:
        name: eingram23.kubernetes.manifest
        tasks_from: apply_url
      vars:
        manifest_url: "https://raw.githubusercontent.com/longhorn/longhorn/v1.3.1/deploy/prerequisite/longhorn-iscsi-installation.yaml"
        manifest: "longhorn-iscsi-installation"

    - name: Pause for 20 seconds
      ansible.builtin.pause:
        seconds: 20

    - name: Deploy longhorn manifest
      ansible.builtin.include_role:
        name: eingram23.kubernetes.manifest
        tasks_from: apply_url
      vars:
        manifest_url: "https://raw.githubusercontent.com/longhorn/longhorn/v1.3.1/deploy/longhorn.yaml"
        manifest: "longhorn"

    - name: Remove longhorn-iscsi-install pods
      ansible.builtin.include_role:
        name: eingram23.kubernetes.manifest
        tasks_from: delete
      vars:
        manifest: "longhorn-iscsi-install"