apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-operator-app-download
  namespace: splunk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-homelab-dev
  resources:
    requests:
      storage: 1Gi