- name: Copy nginx-test manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  loop:
    - nginx-deployment.yaml
    - nginx-ingress.yaml
    - nginx-service.yaml

- name: Deploy longhorn-ui
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ manifest_item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - nginx-deployment.yaml
    - nginx-service.yaml
    - nginx-ingress.yaml
  loop_control:
    loop_var: manifest_item