---
- name: Create staging folders
  ansible.builtin.file:
    path: "{{ dest }}"
    state: directory
    mode: '0755'

- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: test
    api_version: v1
    kind: Namespace
    state: present
    # kubeconfig: "{{ kubeconfig }}"

- name: Copy nginx-test manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"

- name: Deploy nginx-test
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    # kubeconfig: "{{ kubeconfig }}"
  loop:
    - nginx-pvc.yaml
    - nginx-deployment.yaml
    - nginx-service.yaml
    - nginx-ingressroute.yaml
