prom_oper_ver: "v0.62.0"
vmware_exporter_ver: "v0.18.4"
# grafana_helm_ver: "6.50.1"
grafana_helm_ver: "6.57.0"
# node_exporter_ver: "v1.3.1"
node_exporter_ver: "v1.5.0"
# kube_rbac_proxy_ver: "v0.12.0"
kube_rbac_proxy_ver: "v0.14.0"