---
- name: Create staging folders
  ansible.builtin.file:
    path: "{{ dest }}"
    state: directory
    mode: '0755'

- name: Download metallb definitions manifest
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_ver }}/config/manifests/metallb-native.yaml"
    dest: "{{ dest }}{{ metallb_manifest }}"
    mode: '0644'

- name: Deploy metallb
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ metallb_manifest }}"
    # kubeconfig: "{{ kubeconfig }}"
  register: metallb

- name: Pause for 20 seconds
  ansible.builtin.pause:
    seconds: 20
  when: metallb.changed

- name: Create metallb-ippool manifest on host
  ansible.builtin.template:
    src: metallb-ippool.yaml.j2
    dest: "{{ dest }}metallb-ippool.yaml"
    mode: '0644'

- name: Wait for metallb pods become ready
  shell: "kubectl wait --namespace=metallb-system --for=condition=Ready pods --all --timeout=600s"

- name: Deploy metallb ippool
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}metallb-ippool.yaml"
    # kubeconfig: "{{ kubeconfig }}"
