---
- name: Download metallb definitions manifest
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_ver }}/config/manifests/metallb-native.yaml"
    dest: "~/metallb-native.yaml"
    mode: '0644'

- name: Deploy metallb
  kubernetes.core.k8s:
    state: present
    src: "~/metallb-native.yaml"
  register: metallb

- name: Pause for 20 seconds
  ansible.builtin.pause:
    seconds: 20
  when: metallb.changed

- name: Wait for metallb pods to become ready
  shell: "kubectl wait --namespace=metallb-system --for=condition=Ready pods --all --timeout=600s"

- name: Deploy metallb ippool
  kubernetes.core.k8s:
    state: present
    template: "metallb-ippool.yaml.j2"
