{
 "title": "Energy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current Energy Usage ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "kW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "rainforest_emu_2_power" }
     ]
    }
   ]
  },
  {
   "title": "Monthly Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT last(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'energy_monthly') AND $timeFilter GROUP BY time(1M) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "energy_monthly" }
     ]
    }
   ]
  },
  {
   "title": "Daily Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "Daily",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT mean(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'energy_daily') AND $timeFilter GROUP BY time(24h) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "energy_daily" }
     ]
    }
   ]
  },
  {
   "title": "Monthly Energy Usage (kWh)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Monthly",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "energy_monthly" }
     ]
    }
   ]
  }
 ]
}