apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: traefik
    release: prometheus
    name: traefik
  name: traefik
  namespace: monitoring
spec:
  endpoints:
  - port: metrics
    interval: 60s
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: traefik