- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: postgres
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Create secret for deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: postgres-secrets
        namespace: postgres
      type: Opaque
      data:
        defaultpassword: "{{ defaultpassword | b64encode }}"
    state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Download manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"

- name: Create manifests on host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ dest }}{{ item }}"
  loop:
    - postgres-deployment.yaml
    - postgres-ingressroute.yaml
    - pgadmin-deployment.yaml
    - pgadmin-ingressroute.yaml

- name: Deploy postgres + pgadmin
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - pgadmin-configmap.yaml
    - postgres-pvc.yaml
    - pgadmin-pvc.yaml
    - postgres-service.yaml
    - pgadmin-service.yaml
    - postgres-deployment.yaml
    - pgadmin-deployment.yaml
    - postgres-ingressroute.yaml
    - pgadmin-ingressroute.yaml
