apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: node-exporter-ext
    jobLabel: node-exporter-ext
  name: yc-appsrv1-dev
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.3.0.23
  ports:
  - name: https
    port: 9100
    protocol: TCP