apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-ext
  name: yc-appsrv1-dev
  namespace: monitoring
spec:
  externalName: yc-appsrv1-dev
  ports:
  - name: https
    port: 9100
    targetPort: https
  selector:
    app.kubernetes.io/name: node-exporter-ext
  type: ExternalName