apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-ext
    name: node-exporter-ext
  name: node-exporter-ext
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: https
    scheme: https
    tlsConfig:
      - name: ca
        valueFrom:
          secretKeyRef:
            name: rootca
            key: ca.crt
      - name: cert
        valueFrom:
          secretKeyRef:
            name: prometheus-tls
            key: tls.crt
      - name: keySecret
        valueFrom:
          secretKeyRef:
            name: prometheus-tls
            key: tls.key
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter-ext