apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-ext
    name: node-exporter-ext
  name: node-exporter-ext
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: https
    scheme: https
    tlsConfig:
      ca: 
        name: rootca
        key: ca.rt
      cert:
        name: prometheus-tls
        key: tls.crt
      keySecret:
        name: prometheus-tls
        key: tls.key
  jobLabel: node-exporter-ext
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter-ext