apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-ext
    name: node-exporter-ext
  name: node-exporter-ext
  namespace: monitoring
spec:
  endpoints:
    interval: 15s
    port: https
    scheme: https
    tlsConfig:
      ca: rootca
      cert: prom-tls-crt
      keySecret: prom-tls-key
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter-ext