---
- name: Create staging folders
  ansible.builtin.file:
    path: "{{ dest }}"
    state: directory
    mode: '0755'

- name: Create external-secrets k8s namespace
  kubernetes.core.k8s:
    name: external-secrets
    api_version: v1
    kind: Namespace
    state: present

- name: Download external-secrets CRD bundle
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/external-secrets/external-secrets/{{ external_secrets_ver }}/deploy/crds/bundle.yaml
    dest: "{{ dest }}external-secrets-crd.yaml"
    mode: '0644'

- name: Add external-secrets chart repo
  kubernetes.core.helm_repository:
    name: external-secrets
    repo_url: "https://charts.external-secrets.io"

- name: Install external-secrets chart from repo
  kubernetes.core.helm:
    release_name: external-secrets
    release_namespace: external-secrets
    create_namespace: false
    chart_ref: external-secrets/external-secrets
    chart_version: "{{ external_secrets_chart_ver }}"
    wait: true
    update_repo_cache: true
    skip_crds: true

- name: Download files to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  loop:
    - vault-clustersecretstore.yaml

- name: Create vault secret
  ansible.builtin.shell:
    cmd: >
      kubectl create secret generic vault-secretid
      --namespace external-secrets
      --dry-run=client
      --from-literal=secret={{ lookup('hashi_vault', 'secret/approle/ansible:secret_id') }}
      -o yaml | kubectl apply -f -

- name: Deploy external-secrets manifests
  kubernetes.core.k8s:
    src: "{{ item }}"
    namespace: external-secrets
  loop:
    - vault-clustersecretstore.yaml
