- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: calibre
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Download manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"

- name: Create calibre manifests on host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ dest }}{{ item }}"
    mode: '0644'
  loop:
    - calibre-deployment.yaml
    - calibre-ingressroute.yaml
    - calibre-web-ingressroute.yaml
    - calibre-cert.yaml
    - calibre-web-cert.yaml

- name: Deploy calibre
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - calibre-pvc.yaml
    - calibre-service.yaml
    - calibre-deployment.yaml
    - calibre-middleware.yaml
    - calibre-ingressroute.yaml
    - calibre-web-ingressroute.yaml
    - calibre-cert.yaml
    - calibre-web-cert.yaml