apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data-pvc
  namespace: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-homelab
  resources:
    requests:
      storage: 10Gi