- name: Create traefik manifests
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ dest }}{{ item }}"
    mode: '0644'
  loop:
    - traefik-ingressroute-{{ cert }}.yaml
    - traefik-cert-{{ cert }}.yaml

- name: Get svc info
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: traefik
    namespace: kube-system
    # kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: service

- name: Set ip_address
  ansible.builtin.set_fact:
    ip_address: "{{ service | json_query('resources[0].status.loadBalancer.ingress[0].ip') }}"

- name: Add traefik GCP DNS record
  ansible.builtin.include_role:
    name: eingram23.gcp.cloud_dns
    tasks_from: add
    # apply:
    #   delegate_to: localhost
  vars:
    appname: traefik{{ suffix }}
    target: "{{ ip_address }}"
  when: cert != "vault"

- name: Deploy traefik manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    # kubeconfig: "{{ kubeconfig }}"
  loop:
    - traefik-ingressroute-{{ cert }}.yaml
    - traefik-cert-{{ cert }}.yaml

- name: Display IP Address
  ansible.builtin.debug:
    msg: "IP Address is {{ ip_address }}"