- name: Create traefik manifests
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ dest }}{{ item }}"
    mode: '0644'
  loop:
    - traefik-ingressroute.yaml
    - traefik-cert.yaml

- name: Deploy traefik manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - traefik-ingressroute.yaml
    - traefik-cert.yaml
