image:
  pullPolicy: IfNotPresent

service:
  ssh:
    type: LoadBalancer

memcached:
  enabled: true

persistence:
  enabled: true
  size: 10Gi
  storageClass: longhorn-homelab

postgresql:
  enabled: false

gitea:
  additionalConfigFromEnvs:
    - name: GITEA__database__PASSWD
      valueFrom:
        secretKeyRef:
          name: gitea_postgres-secret
          key: password
  config:
    database:
      DB_TYPE: postgresql
      HOST: postgres13.postgres.svc.cluster.local:5432
      NAME: gitea
      USER: gitea
  admin:
    existingSecret: gitea-admin-secret
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  livenessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 200
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 10
  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

