{
 "title": "Climate",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Upstairs Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'upstairs_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Master Bedroom Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'master_bedroom_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Office Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'office_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Charlize's Room Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'charlizes_room_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Bo's Room Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'bos_room_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Upstairs Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\" = 'upstairs_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Main Floor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\" = 'main_floor_humidity') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "main_floor_humidity" }
     ]
    },
    {
     "alias": "Upstairs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "upstairs_humidity" }
     ]
    }
   ]
  },
  {
   "title": "Main Floor Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'main_floor_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Family Room Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'family_room_ecobee_sensor_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Living Room Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'living_room_ecobee_sensor_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Suite Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'suite_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Kitchen Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'kitchen_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Main Floor Humidity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"%\" WHERE (\"entity_id\" = 'main_floor_humidity') AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Upstairs Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Bo's Room",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'bos_room_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "bos_room_temperature" }
     ]
    },
    {
     "alias": "Charlize's Room",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'charlizes_room_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "charlizes_room_temperature" }
     ]
    },
    {
     "alias": "Office",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'office_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "office_temperature" }
     ]
    },
    {
     "alias": "Master Bedroom",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'master_bedroom_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "master_bedroom_temperature" }
     ]
    },
    {
     "alias": "HVAC Heating",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "state",
     "query": "SELECT mean(\"value\") FROM \"state\" WHERE (\"entity_id\" = 'upstairs_hvac_heating') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "upstairs_hvac_heating" }
     ]
    },
    {
     "alias": "HVAC Cooling",
     "query": "SELECT mean(\"value\") FROM \"state\" WHERE (\"entity_id\" = 'upstairs_hvac_cooling') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Main Floor Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Suite",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'suite_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "suite_temperature" }
     ]
    },
    {
     "alias": "Kitchen",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'kitchen_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "kitchen_temperature" }
     ]
    },
    {
     "alias": "HVAC Heating",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "state",
     "query": "SELECT mean(\"value\") FROM \"state\" WHERE (\"entity_id\" = 'main_floor_hvac_heating') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "main_floor_hvac_heating" }
     ]
    },
    {
     "alias": "Family Room",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'family_room_ecobee_sensor_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "family_room_ecobee_sensor_temperature"
      }
     ]
    },
    {
     "alias": "Living Room",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°F",
     "query": "SELECT mean(\"value\") FROM \"°F\" WHERE (\"entity_id\" = 'living_room_ecobee_sensor_temperature') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "living_room_ecobee_sensor_temperature"
      }
     ]
    },
    {
     "alias": "HVAC Cooling",
     "query": "SELECT mean(\"value\") FROM \"state\" WHERE (\"entity_id\" = 'main_floor_hvac_cooling') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "Upstairs HVAC Cooling/Heating Duration",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT distinct(\"value\") FROM \"state\" WHERE (\"entity_id\" = 'upstairs_hvac_cooling') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT distinct(\"value\") FROM \"state\" WHERE (\"entity_id\" = 'upstairs_hvac_heating') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Main Floor HVAC Cooling/Heating Duration",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT distinct(\"value\") FROM \"state\" WHERE (\"entity_id\" = 'main_floor_hvac_cooling') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "query": "SELECT distinct(\"value\") FROM \"state\" WHERE (\"entity_id\" = 'main_floor_hvac_heating') AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  }
 ]
}