---
- name: Create staging folders
  ansible.builtin.file:
    path: "{{ dest }}"
    state: directory
    mode: '0644'

- name: Download alertrules manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  # with_fileglob: "{{ role_path }}/files/alertrules/*"
  loop:
    - "{{ role_path }}/files/alertrules/alertmanager-rules.yaml"
    - "{{ role_path }}/files/alertrules/etcd-rules.yaml"
    - "{{ role_path }}/files/alertrules/prometheus-rules.yaml"

- name: Deploy alertmanager
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item | basename }}"
    # kubeconfig: "{{ kubeconfig }}"
  with_fileglob: "{{ role_path }}/files/alertrules/*"