---
- name: Download k3s manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "{{ role_path }}/files/k3s/*"

- name: Deploy k3s monitoring manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item.path | basename }}"
    kubeconfig: "{{ kubeconfig }}"
  with_fileglob: "{{ role_path }}/files/k3s/*"
