---
- name: Download manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"

- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}monitoring-namespace.yaml"
    kubeconfig: "{{ kubeconfig }}"

- name: Deploy prometheus operator using shell
  ansible.builtin.shell: kubectl apply --server-side -f {{ dest }}prometheus-operator.yaml

- name: Deploy service monitors
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - longhorn-servicemonitor.yaml
    - kubelet-servicemonitor.yaml
    - node-exporter-role.yaml
    - node-exporter-service.yaml
    - node-exporter-daemonset.yaml
    - node-exporter-servicemonitor.yaml
    - kube-state-metrics-role.yaml
    - kube-state-metrics-service.yaml
    - kube-state-metrics-deployment.yaml
    - kube-state-metrics-servicemonitor.yaml
    - kubelet-servicemonitor.yaml
    - traefik-servicemonitor.yaml

- name: Deploy prometheus
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - prometheus.yaml
    - prometheus-service-ext.yaml
    - prometheus-service-local.yaml
    - prometheus-role.yaml
    - prometheus-ingress.yaml

- name: Deploy grafana
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - grafana-pvc.yaml
    - grafana-deployment.yaml
    - grafana-service.yaml
    - grafana-ingress.yaml
