---
- name: Download manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"
  tags: always

- name: Create node-exporter daemonset manifest on host
  ansible.builtin.template:
    src: node-exporter-daemonset.yaml.j2
    dest: "{{ dest }}node-exporter-daemonset.yaml"
    mode: '0644'

- name: Create vmware-exporter deployment manifest on host
  ansible.builtin.template:
    src: vmware-exporter-deployment.yaml.j2
    dest: "{{ dest }}vmware-exporter-deployment.yaml"
    mode: '0644'

- name: Create grafana ingressroute manifests on host
  ansible.builtin.template:
    src: grafana-ingressroute.yaml.j2
    dest: "{{ dest }}grafana-ingressroute.yaml"
    mode: '0644'
  tags: grafana

- name: Create grafana admin password secret
  ansible.builtin.template:
    src: grafana-admin-pass.yaml.j2
    dest: "{{ dest }}grafana-admin-pass.yaml"
    mode: '0644'
  tags: grafana

- name: Create vmware-exporter ingressroute manifests on host
  ansible.builtin.template:
    src: vmware-exporter-ingressroute.yaml.j2
    dest: "{{ dest }}vmware-exporter-ingressroute.yaml"
    mode: '0644'

- name: Create prometheus ingressroute manifests on host
  ansible.builtin.template:
    src: prometheus-ingressroute.yaml.j2
    dest: "{{ dest }}prometheus-ingressroute.yaml"
    mode: '0644'

- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}monitoring-namespace.yaml"
    kubeconfig: "{{ kubeconfig }}"

- name: Deploy prometheus operator using shell
  ansible.builtin.shell: kubectl apply --server-side -f {{ dest }}prometheus-operator.yaml

- name: Create github key
  ansible.builtin.template:
    src: ssh-key-git.key.j2
    dest: /var/tmp/ssh-key-git.key
    mode: '0400'

- name: Pull down prometheus.yml from git
  ansible.builtin.git:
    repo: 'git@github.com:eingram23/configs.git'
    dest: /var/tmp/configs
    key_file: /var/tmp/ssh-key-git.key
    accept_hostkey: true

- name: Create secret for additional prometheus jobs
  ansible.builtin.shell: >
    kubectl create secret generic scrape-configs
    --from-file=/var/tmp/configs/prometheus/prometheus.yml
    --dry-run=client
    --namespace=monitoring
    -o yaml >
    {{ dest }}prom-scrape-servers.yaml

- name: Deploy prometheus job secret
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - prom-scrape-servers.yaml

- name: Clean up tmp files
  ansible.builtin.file:
    path: /var/tmp/configs
    state: absent

- name: Clean up key
  ansible.builtin.file:
    path: /var/tmp/ssh-key-git.key
    state: absent

- name: Deploy monitoring manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - longhorn-servicemonitor.yaml
    - kubelet-servicemonitor.yaml
    - node-exporter-role.yaml
    - node-exporter-service.yaml
    - node-exporter-daemonset.yaml
    - node-exporter-servicemonitor.yaml
    - kube-state-metrics-role.yaml
    - kube-state-metrics-service.yaml
    - kube-state-metrics-deployment.yaml
    - kube-state-metrics-servicemonitor.yaml
    - kubelet-servicemonitor.yaml
    - traefik-servicemonitor.yaml
    - prom-scrape-servers.yaml

- name: Deploy prometheus
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - prometheus.yaml
    - prometheus-service-ext.yaml
    - prometheus-service-local.yaml
    - prometheus-role.yaml
    - prometheus-ingressroute.yaml

- name: Deploy vmware-exporter
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - vmware-exporter-deployment.yaml
    - vmware-exporter-service.yaml
    - vmware-exporter-ingressroute.yaml

- name: Create alertmanager ingressroute
  ansible.builtin.template:
    src: alertmanager-ingressroute.yaml.j2
    dest: "{{ dest }}alertmanager-ingressroute.yaml"
    mode: '0644'

- name: Deploy alertmanager and rules
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - alertmanager.yaml
    - alertmanager-service.yaml
    - alertmanager-main-rules.yaml
    - node-exporter-rules.yaml
    - alertmanager-ingressroute.yaml
    - general-rules.yaml
    - etcd-rules.yaml
    - kube-prometheus-rules.yaml

- name: Deploy grafana secret and ingressroute
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - grafana-ingressroute.yaml
    - grafana-admin-pass.yaml
  tags: grafana

- name: Add hashicorp/vault chart repo
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: "https://grafana.github.io/helm-charts"
  tags: grafana

- name: Install grafana/grafana chart from repo
  kubernetes.core.helm:
    release_name: grafana
    release_namespace: monitoring
    create_namespace: false
    chart_ref: grafana/grafana
    chart_version: "{{ grafana_helm_ver }}"
    wait: true
    update_repo_cache: true
    values_files: "{{ dest }}grafana-values.yaml"
    kubeconfig: "{{ kubeconfig }}"
  tags: grafana

- name: Deploy grafana dashboard configmaps
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - graf-dash-cm-climate.yaml
    # - graf-dash-cm-energy.yaml
    # - graf-dash-cm-windows.yaml
    # - graf-dash-cm-node-exporter.yaml
    # - graf-dash-cm-vmware.yaml
    # - graf-dash-cm-kube-state.yaml
    # - graf-dash-cm-longhorn.yaml
  tags: grafana

- name: Closing comments
  ansible.builtin.debug:
    msg: "Set password for InfluxDB"