- name: Create github key
  ansible.builtin.template:
    src: ssh-key-git.key.j2
    dest: /var/tmp/ssh-key-git.key
    mode: '0400'

- name: Pull down prometheus.yml from git
  ansible.builtin.git:
    repo: 'git@github.com:eingram23/configs.git'
    dest: /var/tmp/configs
    key_file: /var/tmp/ssh-key-git.key
    accept_hostkey: true

- name: Create secret for additional prometheus jobs
  ansible.builtin.shell: >
    kubectl create secret generic scrape-configs
    --from-file=/var/tmp/configs/prometheus/prometheus.yml
    --dry-run=client
    --namespace=monitoring
    -oyaml >
    {{ dest }}prom-scrape-servers.yaml

- name: Deploy prometheus job secret
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - prom-scrape-servers.yaml

- name: Clean up tmp files
  ansible.builtin.file:
    path: /var/tmp/configs
    state: absent

- name: Clean up key
  ansible.builtin.file:
    path: /var/tmp/ssh-key-git.key
    state: absent