---
- name: Install {{ app_name }} chart from repo
  kubernetes.core.helm:
    release_name: "{{ app_name }}"
    release_namespace: "{{ app_name }}"
    create_namespace: true
    chart_ref: "{{ app_name }}/ingress-nginx"
    chart_version: "{{ ingress_nginx_ver }}"
    wait: true
    update_repo_cache: true
