kind: Service
apiVersion: v1
metadata:
  name: unifi-tcp
  namespace: unifi
  annotations:
    ako.vmware.com/enable-shared-vip: "shared-vip-key-1"
spec:
  selector:
    app: unifi-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: control
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: api
    - protocol: TCP
      port: 8843
      targetPort: 8843
      name: https
    - protocol: TCP
      port: 8880
      targetPort: 8880
      name: http
    - protocol: TCP
      port: 6789
      targetPort: 6789
      name: speedtest
  type: LoadBalancer
  # loadBalancerIP: 10.80.0.19

---

kind: Service
apiVersion: v1
metadata:
  name: unifi-udp
  namespace: unifi
  annotations:
    ako.vmware.com/enable-shared-vip: "shared-vip-key-1"
spec:
  selector:
    app: unifi-controller
  ports:
    - protocol: UDP
      port: 3478
      targetPort: 3478
      name: stun
  type: LoadBalancer
  # loadBalancerIP: 10.80.0.19

