- name: Create gitea k8s namespace
  kubernetes.core.k8s:
    name: gitea
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubeconfig }}"
    
- name: Add gitea-charts/gitea chart repo
  kubernetes.core.helm_repository:
    name: gitea-charts
    repo_url: "https://dl.gitea.io/charts/"

- name: Create gitea secrets and values
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ dest }}{{ item }}"
    mode: '0644'
  loop:
    - gitea-admin-secret.yaml
    - gitea-postgres-secret.yaml
    - gitea-cert.yaml
    - gitea-values.yaml

# - name: Create gitea postgres secret
#   ansible.builtin.template:
#     src: gitea-postgres-secret.yaml.j2
#     dest: "{{ dest }}gitea-postgres-secret.yaml"
#     mode: '0644'

# - name: Create gitea values
#   ansible.builtin.template:
#     src: gitea-values.yaml.j2
#     dest: "{{ dest }}gitea-values.yaml"
#     mode: '0644'

- name: Deploy gitea secrets and cert
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - gitea-admin-secret.yaml
    - gitea-postgres-secret.yaml
    - gitea-cert.yaml

# - name: Download files to host
#   ansible.builtin.copy:
#     src: "{{ item }}"
#     dest: "{{ dest }}"
#     mode: '0644'
#   with_fileglob: "*"

- name: Install gitea-charts/gitea chart from repo
  kubernetes.core.helm:
    release_name: gitea
    release_namespace: gitea
    create_namespace: true
    chart_ref: gitea-charts/gitea
    chart_version: "{{ gitea_chart_ver }}"
    wait: true
    update_repo_cache: true
    values_files: "{{ dest }}gitea-values.yaml"
    kubeconfig: "{{ kubeconfig }}"

# - name: Deploy gitea ingressroute
#   kubernetes.core.k8s:
#     state: present
#     src: "{{ dest }}{{ item }}"
#     kubeconfig: "{{ kubeconfig }}"
#   loop:
#     - gitea-ingressroute.yaml