---
- name: Export gitea certs
  ansible.builtin.shell: |
    kubectl get secret gitea-tls -n gitea -o jsonpath="{.data.tls\.key}"|base64 --decode > {{ dest }}gitea-tls.key
    chmod 400 /etc/rancher/k3s/gitea-tls.key
    kubectl get secret gitea-tls -n gitea -o jsonpath="{.data.tls\.crt}"|base64 --decode > {{ dest }}gitea-tls.crt
    kubectl get secret gitea-tls -n gitea -o jsonpath="{.data.ca\.crt}"|base64 --decode > {{ dest }}gitea-ca.crt
  delegate_to: localhost
  run_once: true

- name: Create /etc/rancher/k3s if missing
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0755'

- name: Create registries.yaml file on host
  ansible.builtin.template:
    src: registries.yaml.j2
    dest: /etc/rancher/k3s/registries.yaml
    mode: '0400'

- name: Copy gitea certs to host
  ansible.builtin.copy:
    src: "{{ dest }}{{ item }}"
    dest: /etc/rancher/k3s/
    mode: '0400'
  loop:
    - gitea-tls.key
    - gitea-tls.crt
    - gitea-ca.crt
  notify: Restart k3s