apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-test-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-default
  resources:
    requests:
      storage: 10Gi