---
- name: Run k3s install script
  ansible.builtin.shell: >
    curl -sfL https://get.k3s.io |
    INSTALL_K3S_VERSION={{ ver }}
    K3S_TOKEN={{ k3s_token }}
    sh -s - agent
    --server https://{{ k3s_master }}.local.lan:6443
    --selinux
    --snapshotter=stargz

- name: Install k3s service
  ansible.builtin.systemd:
    name: k3s-agent
    enabled: true
    state: started
