---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Set fact for --disable=traefik
  ansible.builtin.set_fact:
    disable_traefik: "{{ '--disable=traefik' }}"
  when: "'traefik' not in hostvars['localhost']['base_components']"

- name: Install k3s with etcd database
  when:
    - ansible_facts['services']['k3s.service']['status'] is not defined
    - "'vsphere_csi' not in hostvars['localhost']['base_components']"
  ansible.builtin.shell: >
    curl -sfL https://get.k3s.io |
    INSTALL_K3S_VERSION={{ k3s_ver }}
    K3S_TOKEN={{ hostvars['localhost']['k3s_token'] }} sh -s - server
    --disable=servicelb
    {{ disable_traefik | default(omit) }}
    --selinux
    --write-kubeconfig-mode 644
    --cluster-init
    --kubelet-arg container-log-max-files=4
    --kubelet-arg container-log-max-size=50Mi
    --kubelet-arg image-gc-high-threshold=50
    --kubelet-arg image-gc-low-threshold=40
    --etcd-expose-metrics=true
    --tls-san {{ hostvars['localhost']['lb_ip'] }}
    --kube-controller-manager-arg 'bind-address=0.0.0.0'
    --kube-proxy-arg 'metrics-bind-address=0.0.0.0'
    --kube-scheduler-arg 'bind-address=0.0.0.0'
    --kube-controller-manager-arg 'terminated-pod-gc-threshold=10'
  register: k3s_cp_install_status

- name: Install k3s with etcd database and vsphere-csi
  when:
    - ansible_facts['services']['k3s.service']['status'] is not defined
    - "'vsphere_csi' in hostvars['localhost']['base_components']"
  block:
    - name: Get VM ID
      delegate_to: localhost
      community.vmware.vmware_vm_info:
        hostname: vcsa-1.local.lan
        username: "{{ lookup('hashi_vault', 'secret/vsphere/vcsa:vsphere_username') }}"
        password: "{{ lookup('hashi_vault', 'secret/vsphere/vcsa:vsphere_password') }}"
        validate_certs: false
        vm_name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
      register: vm_info

    - name: Install k3s with etcd database and vsphere-csi
      ansible.builtin.shell: >
        curl -sfL https://get.k3s.io |
        INSTALL_K3S_VERSION={{ k3s_ver }}
        K3S_TOKEN={{ hostvars['localhost']['k3s_token'] }} sh -s - server
        --disable=servicelb
        --disable-cloud-controller
        --disable local-storage
        {{ disable_traefik | default(omit) }}
        --selinux
        --write-kubeconfig-mode 644
        --cluster-init
        --kubelet-arg container-log-max-files=4
        --kubelet-arg container-log-max-size=50Mi
        --kubelet-arg image-gc-high-threshold=50
        --kubelet-arg image-gc-low-threshold=40
        --kubelet-arg cloud-provider=external
        --kubelet-arg provider-id=vsphere://{{ vm_info.virtual_machines[0].moid }}
        --etcd-expose-metrics=true
        --tls-san {{ hostvars['localhost']['lb_ip'] }}
        --kube-controller-manager-arg 'bind-address=0.0.0.0'
        --kube-proxy-arg 'metrics-bind-address=0.0.0.0'
        --kube-scheduler-arg 'bind-address=0.0.0.0'
        --kube-controller-manager-arg 'terminated-pod-gc-threshold=10'
      register: k3s_cp_install_status

- name: Check installation status
  debug:
    var: k3s_cp_install_status

- name: Install k3s service
  ansible.builtin.systemd_service:
    name: k3s
    enabled: true
    state: started

- name: Wait until k3s is ready
  ansible.builtin.wait_for:
    host: localhost
    port: 6443
    delay: 10
    timeout: 300
    state: started
  register: k3s_ready
  until: k3s_ready is succeeded
