---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Create k3s config directory
  ansible.builtin.file:
    path: "/etc/rancher/k3s/config.yaml.d"
    state: directory
    mode: '0755'
    recurse: true