---
# - name: SELinux policy
#   ansible.builtin.shell: |
#     ausearch -c 'iptables' --raw | audit2allow -M my-iptables
#     semodule -X 300 -i my-iptables.pp

- name: Disable swap for current session
  when: ansible_swaptotal_mb > 0
  ansible.builtin.command: swapoff -a
  
- name: Disable swap permanently, persist reboots
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    line: '#\1\2\3swap\4'
    backrefs: true
    backup: true

- name: Disable firewall (RHEL/Rocky)
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: Setup dedicated volume for storage
  when: storage == "longhorn"
  block:
    - name: Create mount point
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/storage
        state: directory
        mode: '0700'

    - name: Partition and format disk
      community.general.parted:
        device: /dev/sdb
        number: 1
        state: present
        fs_type: xfs

    - name: Create an xfs filesystem on /dev/sdb1
      community.general.filesystem:
        fstype: xfs
        dev: /dev/sdb1

    - name: Mount disks
      ansible.posix.mount:
        path: /var/lib/rancher/k3s/storage
        src: /dev/sdb1
        fstype: xfs
        state: mounted
