---
- name: Disable swap for current session
  when: ansible_swaptotal_mb > 0
  ansible.builtin.command: swapoff -a

- name: Disable swap permanently, persist reboots
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    line: '#\1\2\3swap\4'
    backrefs: true
    backup: true

- name: Disable firewall (RHEL/Rocky)
  when: ansible_os_family == 'RedHat'
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: false

- name: Setup dedicated volume for storage
  when: "'longhorn' in hostvars['localhost']['base_components']"
  block:
    - name: Check that /dev/sdb exist
      ansible.builtin.command: ls /dev/sdb
      register: check_sdb
      changed_when: false
      ignore_errors: true

    - name: Fail if /dev/sdb doesn't exist
      when: check_sdb.stdout == ""
      ansible.builtin.fail:
        msg: /dev/sdb does not exist, cannot create Longhorn storage

    - name: Create mount point
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/storage
        state: directory
        mode: '0700'

    - name: Partition and format disk
      community.general.parted:
        device: /dev/sdb
        number: 1
        state: present
        fs_type: xfs

    - name: Create an xfs filesystem on /dev/sdb1
      community.general.filesystem:
        fstype: xfs
        dev: /dev/sdb1

    - name: Mount disks
      ansible.posix.mount:
        path: /var/lib/rancher/k3s/storage
        src: /dev/sdb1
        fstype: xfs
        state: mounted
