---
# - name: Check if already installed
#   ansible.builtin.stat:
#     path: /usr/local/bin/k3s
#   register: k3s_installed

- name: Run k3s install script
  ansible.builtin.shell: >
    curl -sfL https://get.k3s.io |
    INSTALL_K3S_VERSION={{ k3s_version }}
    K3S_TOKEN={{ host_prefix }} 
    sh -s - agent --server https://{{ host_prefix }}1.local.lan:6443
  # --disable=servicelb
  # --write-kubeconfig-mode 644
  # when: not k3s_installed.stat.exists

- name: Install k3s service
  ansible.builtin.systemd:
    name: k3s-agent
    enabled: true
    state: started