---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Create k3s config directory
  ansible.builtin.file:
    path: "/etc/rancher/k3s/config.yaml.d"
    state: directory
    mode: '0755'
    recurse: true

- name: Create k3s base config file for worker nodes
  ansible.builtin.template:
    src: "worker.yaml.j2"
    dest: "/etc/rancher/k3s/config.yaml"
    mode: '0644'

- name: Create vsphere_csi config file
  when: "'vsphere_csi' in hostvars['localhost']['base_components']"
  block:
    - name: Get VM ID
      delegate_to: localhost
      community.vmware.vmware_vm_info:
        hostname: vcsa-1.local.lan
        username: "{{ lookup('hashi_vault', 'secret/vsphere/vcsa:vsphere_username') }}"
        password: "{{ lookup('hashi_vault', 'secret/vsphere/vcsa:vsphere_password') }}"
        validate_certs: false
        vm_name: "{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
      register: vm_info

    - name: Create vsphere_csi config file
      ansible.builtin.template:
        src: "vsphere_csi_worker.yaml.j2"
        dest: "/etc/rancher/k3s/config.yaml.d/vsphere-csi.yaml"
        mode: '0644'

- name: Run k3s install script
  when:
    - ansible_facts['services']['k3s-agent.service']['status'] is not defined
  ansible.builtin.shell: >
    curl -sfL https://get.k3s.io |
    INSTALL_K3S_VERSION={{ k3s_ver }}
    K3S_TOKEN={{ hostvars['localhost']['k3s_token'] }}
    sh -s - agent
  register: k3s_agent_install_status

- name: Debug k3s install status
  ansible.builtin.debug:
    var: k3s_agent_install_status

- name: Install k3s service
  ansible.builtin.systemd:
    name: k3s-agent
    enabled: true
    state: started
