kind: Service
apiVersion: v1
metadata:
  name: unifi-tcp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-shared-svc"
spec:
  selector:
    app: unifi-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: control
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: api
    - protocol: TCP
      port: 8843
      targetPort: 8843
      name: https
    - protocol: TCP
      port: 8880
      targetPort: 8880
      name: http
    - protocol: TCP
      port: 6789
      targetPort: 6789
      name: speedtest
  type: LoadBalancer 
  LoadBalancerIP: 10.10.0.231

---

kind: Service
apiVersion: v1
metadata:
  name: unifi-udp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-shared-svc"
spec:
  selector:
    app: unifi-controller
  ports:
    - protocol: UDP
      port: 3478
      targetPort: 3478
      name: stun
  type: LoadBalancer 
  LoadBalancerIP: 10.10.0.231
