apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-homelab
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-cert-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-homelab
  resources:
    requests:
      storage: 10Gi