dest: "/opt/kubernetes/defs/"
kubeconfig: "/etc/rancher/k3s/k3s.yaml"
privkey: "{{ lookup('hashi_vault', 'secret=secret/git/ssh:key') }}"
suffix: "{{ env | default([]) }}"
prom_ver: "v2.40.1"
vmware_exporter_ver: "v0.18.4"
grafana_ver: "8.5.15"
