- name: Install go
  ansible.builtin.package:
    name: go
    state: present
  become: true
  become_method: sudo

- name: Create certstrap folder
  ansible.builtin.file:
    path: certstrap
    state: directory
    mode: '0755'

- name: Clone certstrap git
  ansible.builtin.git:
    repo: https://github.com/square/certstrap
    dest: certstrap

- name: Build certstrap
  ansible.builtin.shell: 
    cmd: |
      cd certstrap
      go build

- name: Create certstrap subfolders
  ansible.builtin.file:
    path: ./certstrap/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - csr
    - out

- name: Copy vault.ca to certstrap out folder
  ansible.builtin.copy:
    src: "{{ dest }}vault.ca"
    dest: ./certstrap/out/vault{{ suffix }}.ca
    remote_src: true
    mode: '0644'

- name: Copy certstrap binary to bin folder
  ansible.builtin.copy:
    src: ./certstrap/certstrap
    dest: /usr/local/bin/
    remote_src: true
    mode: 'u+x,g+x,o+x'
  become: true
  become_method: sudo

- name: Create certstrap-sign-int.sh and cat-certs.sh on host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: ./{{ item }}
    mode: 'u+x'
  loop:
    - cat-certs.sh
    - certstrap-sign-int.sh

- name: Copy scripts to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ./
    mode: 'u+x'
  loop:
    - certstrap-init.sh

- name: Copy csr to certstrap folder
  ansible.builtin.copy:
    src: vault_int{{ suffix }}.csr
    dest: ./certstrap/csr
    mode: '0644'
    remote_src: true

# - name: Pause to copy certs to host
#   ansible.builtin.pause:
#     prompt: Copy certs

# - name: Create Int CA
#   ansible.builtin.shell: |
#     chmod 440 ~/certstrap/out/Homelab_local.lan_Root_CA*
#     ./certstrap-sign-int.sh
#     ./cat-certs.sh

# - name: Get content of cat cert
#   ansible.builtin.slurp:
#     src: "certstrap/out/Homelab_local.lan_Root_Int{{ suffix }}_CA.crt"
#   register: int_cert_enc

# - name: Decode remote content
#   ansible.builtin.set_fact:
#     int_cert: "{{ int_cert_enc['content'] | b64decode }}"

# - name: Output int cert
#   ansible.builtin.debug:
#     var: int_cert