- name: Install go
  ansible.builtin.package:
    name: go
    state: present

- name: Create certstrap folder
  ansible.builtin.file:
    path: "{{ certstrap_dest }}"
    state: directory
    mode: '0700'

- name: Clone certstrap git
  ansible.builtin.git:
    repo: https://github.com/square/certstrap
    dest: "{{ certstrap_dest }}"

- name: Build certstrap
  ansible.builtin.shell: 
    cmd: |
      cd {{ certstrap_dest }}
      go build

- name: Create certstrap subfolders
  ansible.builtin.file:
    path: "{{ certstrap_dest }}{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - csr
    - out

- name: Copy certstrap binary to bin folder
  ansible.builtin.copy:
    src: "{{ certstrap_dest }}/certstrap"
    dest: /usr/local/bin/
    remote_src: true
    mode: 'o+x'

