---
- name: Generate Int CSR
  ansible.builtin.shell:
    cmd: |
      kubectl exec vault-0 -n vault -- vault write -format=json pki_int/intermediate/generate/internal common_name="Homelab{{ suffix }} local.lan Intermediate Authority" key_type="rsa" key_bits="2048" ou="Homelab" organization="Homelab{{ suffix }} Org" country="US" locality="Homelab" province="California" > {{ dest }}vault_int{{ suffix }}_csr
      cat {{ dest }}vault_int{{ suffix }}_csr | jq -r '.data.csr' > {{ dest }}vault_int{{ suffix }}.csr

- name: Get contents of vault_int.csr
  ansible.builtin.slurp:
    src: "{{ dest }}vault_int{{ suffix }}.csr"
  register: vault_int_csr_enc

- name: Decode vault_int_csr
  ansible.builtin.set_fact:
    vault_int_csr: "{{ vault_int_csr_enc['content'] | b64decode }}"
