---
- name: Download manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"

- name: Add hashicorp/vault chart repo
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: "https://helm.releases.hashicorp.com"

- name: Install hashicorp/vault chart from repo
  kubernetes.core.helm:
    release_name: vault
    release_namespace: vault
    create_namespace: true
    chart_ref: hashicorp/vault
    wait: true
    update_repo_cache: true
    values:
      injector:
        enabled: false
    kubeconfig: "{{ kubeconfig }}"

- name: Wait 10 seconds for vault pod to start
  ansible.builtin.pause:
    seconds: 10

# - name: Export cluster-keys.json
#   kubernetes.core.k8s_exec:
#     namespace: vault
#     pod: vault-0
#     command: >-
#       sh -ec "vault operator init -key-shares=1 -key-threshold=1 -format=json > /home/ansible/cluster-keys.json"
#     kubeconfig: "{{ kubeconfig }}"

- name: Export cluster-keys.json
  ansible.builtin.shell:
    cmd: |
      kubectl exec vault-0 -n vault -- vault operator init -key-shares=1 -key-threshold=1 -format=json > cluster-keys.json
      VAULT_UNSEAL_KEY=$(jq -r ".unseal_keys_b64[]" cluster-keys.json)
      kubectl exec vault-0 -n vault -- vault operator unseal $VAULT_UNSEAL_KEY

# - name: Set VAULT_UNSEAL_KEY
#   ansible.builtin.shell:
#     cmd: VAULT_UNSEAL_KEY=$(jq -r ".unseal_keys_b64[]" cluster-keys.json)

# - name: Unseal vault
#   kubernetes.core.k8s_exec:
#     namespace: vault
#     pod: vault-0
#     command: vault operator unseal $VAULT_UNSEAL_KEY
#     kubeconfig: "{{ kubeconfig }}"

- name: Deploy vault middleware and ingressroute manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - vault-ingress.yaml
    
- name: Set VAULT_UNSEAL_KEY
  ansible.builtin.shell:
    cmd: jq -r ".root_token" cluster-keys.json
  register: root_token

- name: Show root_token
  ansible.builtin.debug:
    var: root_token.results