---
- name: Upgrade pip3 if needed
  ansible.builtin.pip:
    name: pip
    state: latest

- name: Install cryptography python module
  ansible.builtin.pip:
    name: "{{ pip_item }}"
  loop:
    - rust
    - setuptools_rust
    - cryptography
  loop_control:
    loop_var: pip_item
  # become: true
  # become_method: sudo

- name: Create vault k8s namespace
  kubernetes.core.k8s:
    name: vault
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Download manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"
  
- name: Create key for k8s to sign (for TLS Listener)
  community.crypto.openssl_privatekey:
    path: "{{ dest }}vault.key"
    size: 2048

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ dest }}vault.csr"
    privatekey_path: "{{ dest }}vault.key"
    organizationName: system:nodes
    common_name: system:node:vault.vault.svc

- name: Extract vault.csr contents
  ansible.builtin.shell:
    cat {{ dest }}vault.csr | base64 | tr -d '\r\n' > {{ dest }}vault.csr.contents

- name: get content of remote file
  slurp:
    src: "{{ dest }}vault.csr.contents"
  register: vault_csr_enc

- name: decode remote content
  set_fact:
    vault_csr: "{{ vault_csr_enc['content'] | b64decode }}"

- name: Create vault-csr.yaml file
  ansible.builtin.template:
    src: vault-csr.yaml.j2
    dest: "{{ dest }}vault-csr.yaml"

# - name: Create csr and send to k8s
#   kubernetes.core.k8s:
#     state: present
#     src: "{{ dest }}{{ item }}"
#     kubeconfig: "{{ kubeconfig }}"
#   loop:
#     - vault-csr.yaml

# - name: Approve cert Request
#   ansible.builtin.shell:
#     cmd: kubectl certificate approve vault-csr

- name: Retrieve cert, write out to file, retrieve k8s CA, create secret
  ansible.builtin.shell:
    cmd: |
      serverCert=$(kubectl get csr vault-csr -o jsonpath='{.status.certificate}')
      echo "${serverCert}" | openssl base64 -d -A -out {{ dest }}vault.crt
      kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}' | base64 -d > {{ dest }}vault.ca
      kubectl create secret generic vault-server-tls --namespace vault --from-file=vault.key={{ dest }}vault.key --from-file=vault.crt={{ dest }}vault.crt --from-file=vault.ca={{ dest }}vault.ca

- name: Create vault ingress
  ansible.builtin.template:
    src: vault-ingress.yaml.j2
    dest: "{{ dest }}vault-ingress.yaml"
    mode: '0644'

- name: Create vault-values.yaml file
  ansible.builtin.template:
    src: vault-values.yaml.j2
    dest: "{{ dest }}vault-values.yaml"
    mode: '0644'

- name: Add hashicorp/vault chart repo
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: "https://helm.releases.hashicorp.com"

- name: Install hashicorp/vault chart from repo
  kubernetes.core.helm:
    release_name: vault
    release_namespace: vault
    create_namespace: false
    chart_ref: hashicorp/vault
    wait: true
    update_repo_cache: true
    values_files: "{{ dest }}vault-values.yaml"
    kubeconfig: "{{ kubeconfig }}"

- name: Deploy vault ingress
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - vault-ingress.yaml

- name: Wait until vault pod is scheduled
  kubernetes.core.k8s_info:
    kind: Pod
    wait: yes
    wait_condition:
      type: PodScheduled
      status: true
    name: vault-0
    namespace: vault
    wait_sleep: 10
    wait_timeout: 360
    kubeconfig: "{{ kubeconfig }}"

- name: Check to see if vault is already deployed
  kubernetes.core.k8s_info:
    kind: Pod
    name: vault-0
    namespace: vault
    kubeconfig: "{{ kubeconfig }}"
  register: vault_ready

- block:
    - name: Pause 30 seconds
      ansible.builtin.pause:
        seconds: 30

    - name: Init and export cluster-keys.json
      ansible.builtin.shell:
        cmd: |
          kubectl exec vault-0 -n vault -- vault operator init -key-shares=1 -key-threshold=1 -format=json > init-keys.json
  when: vault_ready | json_query('resources[0].status.conditions[?type==`ContainersReady`].status') | first | bool == false

- name: Unseal vault
  ansible.builtin.shell:
    cmd: |
      VAULT_UNSEAL_KEY=$(jq -r ".unseal_keys_b64[]" init-keys.json)
      kubectl exec vault-0 -n vault -- vault operator unseal $VAULT_UNSEAL_KEY

- ansible.builtin.shell:
    cmd: |
      cat init-keys.json | jq -r ".root_token" > root_token

- block:
    - name: get content of remote file
      slurp:
        src: "root_token"
      register: root_token_enc

    - name: decode remote content
      set_fact:
        root_token: "{{ root_token_enc['content'] | b64decode }}"
  tags:
    - always
    - show_token

- name: Configure vault pki
  ansible.builtin.shell:
    cmd: |
      kubectl exec vault-0 -n vault -- vault login {{ root_token }}
      kubectl exec vault-0 -n vault -- vault secrets enable pki
      kubectl exec vault-0 -n vault -- vault secrets tune -max-lease-ttl=8760h pki
      kubectl exec vault-0 -n vault -- vault write pki/config/urls issuing_certificates="http://vault.vault.svc.cluster.local:8200/v1/pki/ca" crl_distribution_points="http://vault.vault.svc.cluster.local:8200/v1/pki/crl"
      kubectl exec vault-0 -n vault -- vault write pki/roles/local-dot-lan allowed_domains=local.lan allow_subdomains=true max_ttl=72h

- name: Create root Certificate
  ansible.builtin.shell:
    cmd: kubectl exec vault-0 -n vault -- vault write pki/root/generate/internal common_name=local.lan ttl=8760h
  when: create_root == "true"

- name: Create pki policy
  ansible.builtin.shell:
    cmd: |
      kubectl exec vault-0 -n vault -- /bin/sh -c "`cat {{ dest }}pki-policy.sh`"

- name: Configure k8s auth
  ansible.builtin.shell:
    cmd: |
      kubectl exec vault-0 -n vault -- vault auth enable kubernetes
      kubectl exec vault-0 -n vault -- vault write auth/kubernetes/config kubernetes_host="https://kubernetes.default.svc.cluster.local:443"
      kubectl exec vault-0 -n vault -- vault write auth/kubernetes/role/issuer bound_service_account_names=issuer bound_service_account_namespaces=cert-manager policies=pki ttl=20m

- name: Unseal vault
  ansible.builtin.shell:
    cmd: |
      VAULT_UNSEAL_KEY=$(jq -r ".unseal_keys_b64[]" init-keys.json)
      kubectl exec vault-0 -n vault -- vault operator unseal $VAULT_UNSEAL_KEY
  tags:
    - never
    - unseal

- name: Show root_token
  ansible.builtin.debug:
    var: root_token
  tags:
    - always
    - show_token
