apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  name: primary
  namespace: grafana
  labels:
    agent: grafana-agent-logs
spec:
  clients:
  - url: http://loki.local.lan:3100/loki/api/v1/push
    # basicAuth:
    #   username:
    #     name: primary-credentials-logs
    #     key: username
    #   password:
    #     name: primary-credentials-logs
    #     key: password

  # Supply an empty namespace selector to look in all namespaces. Remove
  # this to only look in the same namespace as the LogsInstance CR
  podLogsNamespaceSelector: 
    matchNames:
    - default
    - vault
    - awx
    - cert-manager
    - gitea
    - longhorn-system
    - metallb-system
    - kube-node-lease
    - kube-public
    - kube-system
    - kubernetes-dashboard
  podLogsSelector:
    matchLabels:
      instance: primary