apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-servicemonitor
  namespace: grafana-agent
  labels:
    name: longhorn-servicemonitor
    instance: primary
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - longhorn-system
  endpoints:
  - port: manager
    interval: 60s
  targetLabels:
  - env
