- name: Create unifi k8s namespace
  kubernetes.core.k8s:
    name: unifi
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Download manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"

- name: Create unifi-deployment.yaml manifest on host
  ansible.builtin.template:
    src: unifi-deployment.yaml.j2
    dest: "{{ dest }}unifi-deployment.yaml"

- name: Create unifi-service.yaml manifest on host
  ansible.builtin.template:
    src: unifi-service.yaml.j2
    dest: "{{ dest }}unifi-service.yaml"

- name: Create unifi-ingressroute.yaml manifest on host
  ansible.builtin.template:
    src: unifi-ingressroute.yaml.j2
    dest: "{{ dest }}unifi-ingressroute.yaml"

- name: Deploy unifi
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - unifi-pvc.yaml
    - unifi-service.yaml
    - unifi-deployment.yaml
    - unifi-ingressroute.yaml
