- name: Create unifi k8s namespace
  kubernetes.core.k8s:
    name: unifi
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubeconfig }}"

- name: Download manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "*"

- name: Create template manifests on host
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ dest }}{{ item }}"
    mode: '0644'
  loop:
    - unifi-cert.yaml
    - unifi-deployment.yaml

- name: Deploy unifi
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - unifi-cert-acme.yaml
    - unifi-pvc.yaml
    - unifi-service.yaml
    - unifi-deployment.yaml
