apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-1
  namespace: longhorn-system
spec:
  cron: "* * * * *"
  task: "backup"
  groups:
  - backup
  retain: 1
  concurrency: 2
  # labels:
  #   label/1: a
  #   label/2: b