defaultSettings:
  # backupTarget: s3://b2bucketname@us-west-001/
  backupTarget: nfs://homenas.local.lan:/longhorn_backups
  # backupTargetCredentialSecret: longhorn-s3-secret
  defaultDataLocality: best-effort
  defaultReplicaCount: 2
  defaultLonghornStaticStorageClass: longhorn-homelab-backup
  orphanAutoDeletion: true
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod