defaultSettings:
  # backupTarget: s3://b2bucketname@us-west-001/
  backupTarget: nfs://homenas.local.lan:/mnt/pool0/Shared/Backup/longhorn_backups/backups
  # backupTargetCredentialSecret: longhorn-s3-secret
  defaultDataLocality: best-effort
  defaultReplicaCount: 1
  defaultLonghornStaticStorageClass: longhorn-homelab-dev
  orphanAutoDeletion: true
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod

persistence:
  defaultClassReplicaCount: 1

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1