apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-data-pvc
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ storageclass }}
  resources:
    requests:
      storage: 10Gi

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books-pvc
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ storageclass }}
  resources:
    requests:
      storage: 10Gi