apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vmware-exporter
  name: vmware-exporter
  namespace: monitoring
spec:
  ports:
  - name: web
    protocol: TCP
    port: 9272
    targetPort: web
  selector:
    app.kubernetes.io/name: vmware-exporter
