apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: eso
spec:
  provider:
    vault:
      server: "http://vault.local.lan"
      path: "secret"
      version: "v1"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          # Path where the App Role authentication backend is mounted
          path: "approle"
          # RoleID configured in the App Role authentication backend
          roleId: "78eaf493-f89a-651b-f6b9-24112c6d611d"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-secretid"
            key: "secret"
            namespace: "eso"