---
- name: Download alertrules manifests to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ dest }}"
    mode: '0644'
  with_fileglob: "{{ role_path }}/files/alertrules/*"

- name: Deploy alertmanager
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item | basename }}"
    kubeconfig: "{{ kubeconfig }}"
  with_fileglob: "{{ role_path }}/files/alertrules/*"