apiVersion: v1
kind: ConfigMap
metadata:
  name: graf-dash-cm-energy
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  energy.json: |-
{{ .Files.Get "/opt/kubernetes/defs/energy.json" | indent 4 }}