- name: Copy traefik dashbard ingressroute manifest to host
  ansible.builtin.copy:
    src: traefik-ingressroute.yaml
    dest: "{{ dest }}traefik-ingressroute.yaml"
    mode: '0644'

- name: Create traefik ssl certificate 
  ansible.builtin.template:
    src: traefik-cert.yaml.j2
    dest: "{{ dest }}traefik-cert.yaml"

- name: Deploy traefik manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - traefik-ingressroute.yaml
    - traefik-cert.yaml
