- name: Copy traefik dashbard ingressroute manifest to host
  ansible.builtin.copy:
    src: traefik-ingressroute.yaml
    dest: "{{ dest }}traefik-ingressroute.yaml"
    mode: '0644'

- name: Deploy traefik dashboard ingressroute
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}traefik-ingressroute.yaml"
    kubeconfig: "{{ kubeconfig }}"