apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-ext
  name: node-exporter-ext
  namespace: monitoring
spec:
  externalName: node-exporter-ext
  ports:
  - name: https
    port: 9100
    targetPort: https
  # selector:
  #   app.kubernetes.io/name: node-exporter-ext
  type: ExternalName