apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-ext
    jobLabel: node-exporter-ext
  name: node-exporter-ext
  namespace: monitoring
subsets:
- addresses:
  - ip: 138.68.18.20
  ports:
  - name: https
    port: 9100
    protocol: TCP