apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/name: node-exporter-ext-dev
    jobLabel: node-exporter-ext-dev
  name: node-exporter-ext-dev
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.3.0.23
  ports:
  - name: https
    port: 9100
    protocol: TCP