---
dest: "/var/tmp/defs/"
kubeconfig: "/var/tmp/tanzu.yaml"
tanzu_cp: "10.80.0.10"
tkg_ver: "v1.24.9---vmware.1-tkg.4"
clustername: "tkgs-cluster1"
vmclass: "best-effort-xsmall"
storageclass: "vsan-default-storage-policy"
control_replicas: 1
worker_replicas: 3
vsphere_username: "{{ lookup('hashi_vault', 'secret=secret/vsphere/vcsa:vsphere_username') }}"
vsphere_password: "{{ lookup('hashi_vault', 'secret=secret/vsphere/vcsa:vsphere_password') }}"