---
# VARS: cert, env, master_node
- name: Deploy gitea to k3s
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Assert vars set
      ansible.builtin.assert:
        that:
          - cluster is defined
          - cp_node is defined

    - name: Set environment
      ansible.builtin.import_role:
        name: eingram23.kubernetes.kubeconfig
        tasks_from: create_local_kube

    - name: Deploy gitea
      ansible.builtin.import_role:
        name: eingram23.kubernetes.gitea
        tasks_from: copy_certs
