---
- name: Initial deployment of metallb on new cluster
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Assert necessary vars set
      ansible.builtin.assert:
        that:
          - cluster is defined
          - lb_ip is defined and lb_ip | ansible.utils.ipaddr

    - name: Set environment
      ansible.builtin.import_role:
        name: eingram23.kubernetes.kubeconfig
        tasks_from: create_local_kube

    - name: Deploy metallb
      ansible.builtin.include_role:
        name: eingram23.kubernetes.metallb
