---
- name: Create vault issuer service account
  kubernetes.core.k8s:
    name: issuer
    namespace: cert-manager
    api_version: v1
    kind: ServiceAccount
    state: present
    # kubeconfig: "{{ kubeconfig }}"

- name: Get caBundle data
  ansible.builtin.shell: >
    kubectl config view --minify --raw | grep certificate-authority-data: | sed 's/^.*: //'
  register: cabundle_data

- name: Set fact from cabundle data
  ansible.builtin.set_fact:
    cabundle: "{{ cabundle_data.stdout }}"

- name: Create vault-cluster-issuer.yaml file
  ansible.builtin.template:
    src: vault-cluster-issuer.yaml.j2
    dest: "{{ dest }}vault-cluster-issuer.yaml"
    mode: '0644'

- name: Deploy vault issuer and secret
  kubernetes.core.k8s:
    state: present
    src: "{{ dest }}{{ item }}"
    # kubeconfig: "{{ kubeconfig }}"
  loop:
    - issuer-secret.yaml
    - vault-cluster-issuer.yaml