apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: postgres
spec:
  selector:
    app: pgadmin
  ports:
  - name: web
    port: 80
    targetPort: 80
  # type: LoadBalancer 
  # LoadBalancerIP: {{ pgadmin_ip }}