apiVersion: v1
kind: Service
metadata:
  name: postgres13
  namespace: postgres
spec:
  selector:
    app: postgres13
  ports:
  - name: postgres13
    port: 5432
    targetPort: 5432
  # type: LoadBalancer 
  # LoadBalancerIP: {{ postgres13_ip }}
