apiVersion: v1
kind: Service
metadata:
  name: postgres13
  namespace: default
spec:
  selector:
    app: postgres13
  ports:
  - name: postgres13
    port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
  namespace: default
spec:
  selector:
    app: postgres13
  ports:
  - name: web
    port: 80
    targetPort: 80
