---
- name: Create .kube folder
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0755'

- name: Create kubeconfig
  ansible.builtin.copy:
    content: "{{ kubeconfig }}"
    dest: ~/.kube/config
    mode: '0400'
