- name: Read kubeconfig
  ansible.builtin.slurp:
    src: "/etc/rancher/k3s/k3s.yaml"
  register: kubeconfig_enc

- name: Decode remote content
  ansible.builtin.set_fact:
    kubeconfig: "{{ kubeconfig_enc['content'] | b64decode | from_yaml }}"

- name: Write vault secret
  delegate_to: localhost
  become: false
  community.hashi_vault.vault_write:
    path: "secret/kubernetes/{{ cluster }}"
    data:
      kubeconfig: "{{ lookup('template', 'k3s.yaml.j2') }}"
      token: "{{ hostvars['localhost']['k3s_token'] }}"
