---
- name: Set dev env based on k8s hostname
  when: k8shost is match(".+dev.+")
  ansible.builtin.set_fact:
    env: -dev

# - name: Check for existing kubeconfig file
#   ansible.builtin.stat:
#     path: "~/.kube/config"
#   register: config

# - name: Read kubeconfig file from host
#   when: config.stat.exists
#   block:
#     - name: Read file
#       ansible.builtin.slurp:
#         src: "~/.kube/config"
#       register: kubeconfig_enc

#     - name: Decode remote content
#       ansible.builtin.set_fact:
#         kubeconfig_temp: "{{ kubeconfig_enc['content'] | b64decode }}"

# - name: Create kubeconfig file
#   when: kubeconfig_temp is defined and k8shost not in kubeconfig_temp or
#         kubeconfig_temp is not defined
#   block:

- name: Create .kube folder
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0755'

- name: Create kubeconfig
  ansible.builtin.copy:
    content: "{{ kubeconfig }}"
    dest: ~/.kube/config
    mode: '0400'
